on:
  push:
    branches:
      - gh-pages
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{ runner.OS }}-build-${{ runner.OS }}-

      - name: Install dependencies
        run: yarn install --prod --pure-lockfile

      - name: npm install fs-extra
        run : npm install fs-extra

      - name: Build
        run: yarn build --prefix-paths
        env:
          NODE_ENV: production

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.gatsby-blog }}
          GH_PAT: ${{ secrets.EEYHWJ }}
          BUILD_DIR: 'public/'